/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package block.core;

import blok.interfaces.IUIControler;
import blok.interfaces.IFabricaSimulator;
import blok.interfaces.IFabricaThemes;
import blok.interfaces.ISimulator;
import blok.interfaces.IThemes;
import blok.simulator.factory1.FabricaSimulator;
import blok.simulator.factory1.Simulator;
import blok.simulator.factory2.Simulator3D;

import java.awt.Component;
import java.awt.Container;
import java.awt.Dimension;

import javax.swing.JComboBox;
import javax.swing.JComponent;

import block.themes.factory1.FabricaThemeMontanha;
import block.themes.factory1.MainPanel;
import block.themes.factory2.FabricaThemeGelo;

/**
 *
 * @author sandroandrade
 */
public class MainWindowControler extends javax.swing.JFrame implements IUIControler {
	
	   // Variables declaration - do not modify//GEN-BEGIN:variables
  
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    
    private  IThemes mainPanel;
    private ISimulator simulator ;
    private int option;
	
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form MainWindow
     */
    public MainWindowControler(int option) {
    	 this.option = option;
        
    	 initComponents();
        
        
    }
    
    @Override
	public void init() {
    		this.setVisible(true);
	}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    public void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
   
 

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);
        
     

        setJMenuBar(jMenuBar1);
        
       Dimension size = new Dimension(1000, 600);
        
        IFabricaSimulator fabrica=null;
        IFabricaThemes fabricaThema = null;
        
        fabrica= new FabricaSimulator();
   
        switch (this.option) {
			case 1:
				fabricaThema = new FabricaThemeMontanha();
				break;
				
			case 2:
				fabricaThema = new FabricaThemeGelo();
				break;

			default:
				break;
			}
      
        mainPanel =fabricaThema.createTheme();
       
        ((JComponent) mainPanel).setPreferredSize(size);
        ((JComponent) mainPanel).setPreferredSize(size);
        ((Component) mainPanel).setMinimumSize(size);
        ((Component) mainPanel).setMaximumSize(size);
        ((Component) mainPanel).setSize(size);
        setContentPane((Container) mainPanel);

        setResizable(false);
        pack();
        
       
         simulator = fabrica.createSimulator(mainPanel);
        mainPanel.setSimulator(simulator);
        simulator.init();
        

        pack();
    }// </editor-fold>//GEN-END:initComponents



}
